// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v \
// RUN:   -target-feature +zvfhmin \
// RUN:   -target-feature +experimental-zvvmttls \
// RUN:   -O2 -emit-llvm %s -o - | FileCheck %s

// Transposing tile store, LMUL=1, every element type IME exposes at the
// Clang surface: i8/i16/i32/i64 and f16/f32/f64.

#pragma clang riscv intrinsic zvvm_vector

#include <riscv_vector.h>

// CHECK-LABEL: define dso_local void @test_vmtts_v_i8m1
// CHECK-SAME:    (ptr noundef writeonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], <vscale x 8 x i8> [[V:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         tail call void @llvm.riscv.vmtts.nxv8i8.p0.i64(<vscale x 8 x i8> [[V]], ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void test_vmtts_v_i8m1(int8_t *base, size_t ld, vint8m1_t v, size_t vl) {
  __riscv_vmtts_v_i8m1(base, ld, v, vl);
}

// CHECK-LABEL: define dso_local void @test_vmtts_v_i16m1
// CHECK-SAME:    (ptr noundef writeonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], <vscale x 4 x i16> [[V:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         tail call void @llvm.riscv.vmtts.nxv4i16.p0.i64(<vscale x 4 x i16> [[V]], ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void test_vmtts_v_i16m1(int16_t *base, size_t ld, vint16m1_t v, size_t vl) {
  __riscv_vmtts_v_i16m1(base, ld, v, vl);
}

// CHECK-LABEL: define dso_local void @test_vmtts_v_i32m1
// CHECK-SAME:    (ptr noundef writeonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], <vscale x 2 x i32> [[V:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         tail call void @llvm.riscv.vmtts.nxv2i32.p0.i64(<vscale x 2 x i32> [[V]], ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void test_vmtts_v_i32m1(int32_t *base, size_t ld, vint32m1_t v, size_t vl) {
  __riscv_vmtts_v_i32m1(base, ld, v, vl);
}

// CHECK-LABEL: define dso_local void @test_vmtts_v_i64m1
// CHECK-SAME:    (ptr noundef writeonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], <vscale x 1 x i64> [[V:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         tail call void @llvm.riscv.vmtts.nxv1i64.p0.i64(<vscale x 1 x i64> [[V]], ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void test_vmtts_v_i64m1(int64_t *base, size_t ld, vint64m1_t v, size_t vl) {
  __riscv_vmtts_v_i64m1(base, ld, v, vl);
}

// CHECK-LABEL: define dso_local void @test_vmtts_v_f16m1
// CHECK-SAME:    (ptr noundef writeonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], <vscale x 4 x half> [[V:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         tail call void @llvm.riscv.vmtts.nxv4f16.p0.i64(<vscale x 4 x half> [[V]], ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void test_vmtts_v_f16m1(_Float16 *base, size_t ld, vfloat16m1_t v, size_t vl) {
  __riscv_vmtts_v_f16m1(base, ld, v, vl);
}

// CHECK-LABEL: define dso_local void @test_vmtts_v_f32m1
// CHECK-SAME:    (ptr noundef writeonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], <vscale x 2 x float> [[V:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         tail call void @llvm.riscv.vmtts.nxv2f32.p0.i64(<vscale x 2 x float> [[V]], ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void test_vmtts_v_f32m1(float *base, size_t ld, vfloat32m1_t v, size_t vl) {
  __riscv_vmtts_v_f32m1(base, ld, v, vl);
}

// CHECK-LABEL: define dso_local void @test_vmtts_v_f64m1
// CHECK-SAME:    (ptr noundef writeonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], <vscale x 1 x double> [[V:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         tail call void @llvm.riscv.vmtts.nxv1f64.p0.i64(<vscale x 1 x double> [[V]], ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void test_vmtts_v_f64m1(double *base, size_t ld, vfloat64m1_t v, size_t vl) {
  __riscv_vmtts_v_f64m1(base, ld, v, vl);
}
