// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v \
// RUN:   -target-feature +zvfhmin \
// RUN:   -target-feature +experimental-zvvmtls \
// RUN:   -O2 -emit-llvm %s -o - | FileCheck %s

// Phase 2 surfaces the order-preserving tile load builtin for every LMUL=1
// element type IME exposes at the Clang surface: i8/i16/i32/i64 and
// f16/f32/f64. The instruction encoding is element-type-agnostic (SEW comes
// from vtype.vsew), so each type maps to the same `vmtl.v` pseudo with the
// matching IR overload.

#pragma clang riscv intrinsic zvvm_vector

#include <riscv_vector.h>

// CHECK-LABEL: define dso_local <vscale x 8 x i8> @test_vmtl_v_i8m1
// CHECK-SAME:    (ptr noundef readonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 8 x i8> @llvm.riscv.vmtl.nxv8i8.p0.i64(<vscale x 8 x i8> poison, ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vmtl_v_i8m1(const int8_t *base, size_t ld, size_t vl) {
  return __riscv_vmtl_v_i8m1(base, ld, vl);
}

// CHECK-LABEL: define dso_local <vscale x 4 x i16> @test_vmtl_v_i16m1
// CHECK-SAME:    (ptr noundef readonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 4 x i16> @llvm.riscv.vmtl.nxv4i16.p0.i64(<vscale x 4 x i16> poison, ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vmtl_v_i16m1(const int16_t *base, size_t ld, size_t vl) {
  return __riscv_vmtl_v_i16m1(base, ld, vl);
}

// CHECK-LABEL: define dso_local <vscale x 2 x i32> @test_vmtl_v_i32m1
// CHECK-SAME:    (ptr noundef readonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 2 x i32> @llvm.riscv.vmtl.nxv2i32.p0.i64(<vscale x 2 x i32> poison, ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vmtl_v_i32m1(const int32_t *base, size_t ld, size_t vl) {
  return __riscv_vmtl_v_i32m1(base, ld, vl);
}

// CHECK-LABEL: define dso_local <vscale x 1 x i64> @test_vmtl_v_i64m1
// CHECK-SAME:    (ptr noundef readonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 1 x i64> @llvm.riscv.vmtl.nxv1i64.p0.i64(<vscale x 1 x i64> poison, ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vmtl_v_i64m1(const int64_t *base, size_t ld, size_t vl) {
  return __riscv_vmtl_v_i64m1(base, ld, vl);
}

// CHECK-LABEL: define dso_local <vscale x 4 x half> @test_vmtl_v_f16m1
// CHECK-SAME:    (ptr noundef readonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 4 x half> @llvm.riscv.vmtl.nxv4f16.p0.i64(<vscale x 4 x half> poison, ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vmtl_v_f16m1(const _Float16 *base, size_t ld, size_t vl) {
  return __riscv_vmtl_v_f16m1(base, ld, vl);
}

// CHECK-LABEL: define dso_local <vscale x 2 x float> @test_vmtl_v_f32m1
// CHECK-SAME:    (ptr noundef readonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 2 x float> @llvm.riscv.vmtl.nxv2f32.p0.i64(<vscale x 2 x float> poison, ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vmtl_v_f32m1(const float *base, size_t ld, size_t vl) {
  return __riscv_vmtl_v_f32m1(base, ld, vl);
}

// CHECK-LABEL: define dso_local <vscale x 1 x double> @test_vmtl_v_f64m1
// CHECK-SAME:    (ptr noundef readonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 1 x double> @llvm.riscv.vmtl.nxv1f64.p0.i64(<vscale x 1 x double> poison, ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vmtl_v_f64m1(const double *base, size_t ld, size_t vl) {
  return __riscv_vmtl_v_f64m1(base, ld, vl);
}

// LMUL > 1 spot checks for the order-preserving tile load. The intrinsic
// scales naturally with vtype.LMUL since there's only one tile per call.

// CHECK-LABEL: define dso_local <vscale x 4 x i32> @test_vmtl_v_i32m2
// CHECK-SAME:    (ptr noundef readonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 4 x i32> @llvm.riscv.vmtl.nxv4i32.p0.i64(<vscale x 4 x i32> poison, ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vmtl_v_i32m2(const int32_t *base, size_t ld, size_t vl) {
  return __riscv_vmtl_v_i32m2(base, ld, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i32> @test_vmtl_v_i32m4
// CHECK-SAME:    (ptr noundef readonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 8 x i32> @llvm.riscv.vmtl.nxv8i32.p0.i64(<vscale x 8 x i32> poison, ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vmtl_v_i32m4(const int32_t *base, size_t ld, size_t vl) {
  return __riscv_vmtl_v_i32m4(base, ld, vl);
}

// CHECK-LABEL: define dso_local <vscale x 16 x i32> @test_vmtl_v_i32m8
// CHECK-SAME:    (ptr noundef readonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 16 x i32> @llvm.riscv.vmtl.nxv16i32.p0.i64(<vscale x 16 x i32> poison, ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vmtl_v_i32m8(const int32_t *base, size_t ld, size_t vl) {
  return __riscv_vmtl_v_i32m8(base, ld, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x float> @test_vmtl_v_l4_f32m4
// CHECK-SAME:    (ptr noundef readonly captures(none) [[BASE:%.*]], i64 noundef [[LD:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 8 x float> @llvm.riscv.vmtl.l4.nxv8f32.p0.i64(<vscale x 8 x float> poison, ptr [[BASE]], i64 [[LD]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vmtl_v_l4_f32m4(const float *base, size_t ld, size_t vl) {
  return __riscv_vmtl_v_l4_f32m4(base, ld, vl);
}
