// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 \
// RUN:   -target-feature +v -target-feature +experimental-zvvmm \
// RUN:   -target-feature +experimental-zvvmtls \
// RUN:   -target-feature +experimental-zvvmttls \
// RUN:   -O2 -emit-llvm %s -o - | FileCheck %s

// Phase-2 lambda surface: per-instruction Lλ override variants for the four
// tile load/store mnemonics. Spot-checks one representative lambda per
// mnemonic (covers loads vs stores, order-preserving vs transposing, integer
// vs float vs FP8). Element-type coverage already exists in
// riscv_zvvm_vector.td as the TypeRange "csilxfd" — the foreach over
// "_l1".._l64" multiplies that by 7 lambda variants per mnemonic.

#pragma clang riscv intrinsic zvvm_vector

#include <riscv_vector.h>

// CHECK-LABEL: define dso_local <vscale x 2 x i32> @test_vmtl_l1
// CHECK:         tail call <vscale x 2 x i32> @llvm.riscv.vmtl.l1.nxv2i32
vint32m1_t test_vmtl_l1(const int *ptr, size_t ld, size_t vl) {
  return __riscv_vmtl_v_l1_i32m1(ptr, ld, vl);
}

// CHECK-LABEL: define dso_local <vscale x 2 x i32> @test_vmtl_l4
// CHECK:         tail call <vscale x 2 x i32> @llvm.riscv.vmtl.l4.nxv2i32
vint32m1_t test_vmtl_l4(const int *ptr, size_t ld, size_t vl) {
  return __riscv_vmtl_v_l4_i32m1(ptr, ld, vl);
}

// Largest lambda (L64) on the largest element width (i64).
//
// CHECK-LABEL: define dso_local <vscale x 1 x i64> @test_vmtl_l64_i64
// CHECK:         tail call <vscale x 1 x i64> @llvm.riscv.vmtl.l64.nxv1i64
vint64m1_t test_vmtl_l64_i64(const long *ptr, size_t ld, size_t vl) {
  return __riscv_vmtl_v_l64_i64m1(ptr, ld, vl);
}

// FP variants: lambda override on f32 / f16 tile load.
//
// CHECK-LABEL: define dso_local <vscale x 2 x float> @test_vmtl_l8_f32
// CHECK:         tail call <vscale x 2 x float> @llvm.riscv.vmtl.l8.nxv2f32
vfloat32m1_t test_vmtl_l8_f32(const float *ptr, size_t ld, size_t vl) {
  return __riscv_vmtl_v_l8_f32m1(ptr, ld, vl);
}

// Order-preserving store: builtin arg order (ptr, ld, vec, vl) gets rotated
// to the IR shape (vec, ptr, ld, vl) by the ManualCodegen.
//
// CHECK-LABEL: define dso_local void @test_vmts_l16
// CHECK:         tail call void @llvm.riscv.vmts.l16.nxv2i32{{.*}}(<vscale x 2 x i32> %v, ptr %ptr, i64 %ld, i64 %vl)
void test_vmts_l16(int *ptr, size_t ld, vint32m1_t v, size_t vl) {
  __riscv_vmts_v_l16_i32m1(ptr, ld, v, vl);
}

// Transposing load (Zvvmttls) with per-instruction lambda override.
//
// CHECK-LABEL: define dso_local <vscale x 4 x i16> @test_vmttl_l32_i16
// CHECK:         tail call <vscale x 4 x i16> @llvm.riscv.vmttl.l32.nxv4i16
vint16m1_t test_vmttl_l32_i16(const short *ptr, size_t ld, size_t vl) {
  return __riscv_vmttl_v_l32_i16m1(ptr, ld, vl);
}

// Transposing store (Zvvmttls) with per-instruction lambda override —
// covers the rotated-args path for the transposing variant.
//
// CHECK-LABEL: define dso_local void @test_vmtts_l2_f64
// CHECK:         tail call void @llvm.riscv.vmtts.l2.nxv1f64{{.*}}(<vscale x 1 x double> %v, ptr %ptr, i64 %ld, i64 %vl)
void test_vmtts_l2_f64(double *ptr, size_t ld, vfloat64m1_t v, size_t vl) {
  __riscv_vmtts_v_l2_f64m1(ptr, ld, v, vl);
}
