// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -target-feature +experimental-zvvmm \
// RUN:   -O2 -emit-llvm %s -o - | FileCheck %s

// Phase-2 lambda surface: __riscv_vsetlambda(L) wraps the encoding-form IR
// intrinsics (int_riscv_vsetlambda for L != 0, int_riscv_query_lambda for
// L == 0). The C signature accepts the spec's power-of-two form; Clang
// converts between the user value (0 / 2^k) and the 3-bit vtype.lambda
// encoding (0 / k+1) at IR-gen time.

#pragma clang riscv intrinsic zvvm_vector

#include <riscv_vector.h>

// L == 0: read-only query path. No vsetlambda call; result is converted from
// the established encoding via select(eq, 0, 1 << (enc - 1)).
//
// CHECK-LABEL: define dso_local{{.*}} i64 @test_vsetlambda_0
// CHECK:         [[ENC:%.*]] = tail call i64 @llvm.riscv.query.lambda.i64()
// CHECK-NEXT:    [[ISZERO:%.*]] = icmp eq i64 [[ENC]], 0
// CHECK-NEXT:    [[ENCM1:%.*]] = add i64 [[ENC]], -1
// CHECK-NEXT:    [[POT:%.*]] = shl {{.*}}i64 1, [[ENCM1]]
// CHECK-NEXT:    [[RES:%.*]] = select i1 [[ISZERO]], i64 0, i64 [[POT]]
// CHECK-NEXT:    ret i64 [[RES]]
//
size_t test_vsetlambda_0(void) {
  return __riscv_vsetlambda(0);
}

// L == 1: encoding = 1. Sets lambda to L1.
//
// CHECK-LABEL: define dso_local{{.*}} i64 @test_vsetlambda_1
// CHECK:         tail call i64 @llvm.riscv.vsetlambda.i64(i64 1)
//
size_t test_vsetlambda_1(void) {
  return __riscv_vsetlambda(1);
}

// L == 4: encoding = log2(4) + 1 = 3.
//
// CHECK-LABEL: define dso_local{{.*}} i64 @test_vsetlambda_4
// CHECK:         tail call i64 @llvm.riscv.vsetlambda.i64(i64 3)
//
size_t test_vsetlambda_4(void) {
  return __riscv_vsetlambda(4);
}

// L == 64: encoding = log2(64) + 1 = 7. Largest valid lambda.
//
// CHECK-LABEL: define dso_local{{.*}} i64 @test_vsetlambda_64
// CHECK:         tail call i64 @llvm.riscv.vsetlambda.i64(i64 7)
//
size_t test_vsetlambda_64(void) {
  return __riscv_vsetlambda(64);
}
