// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -target-feature +experimental-zvvi8mm -target-feature +experimental-zvvi16mm -target-feature +experimental-zvvi32mm -target-feature +experimental-zvvi64mm \
// RUN:   -O2 -emit-llvm %s -o - | FileCheck %s

#pragma clang riscv intrinsic zvvm_vector

#include <riscv_vector.h>

// EMUL_C ∈ {1,2,4,8} × LMUL ∈ {1,2,4,8} cross-product. The `_i32m{N}` segment
// of the C-API name encodes the C-tile EMUL_C; the trailing `_lm{N}` encodes
// the A/B LMUL (per the IME C-naming convention; the `_lm1` qualifier is
// omitted for LMUL=1). Spot-check representative cells.

// CHECK-LABEL: define dso_local <vscale x 2 x i32> @test_vmmacc_vv_i32m1
// CHECK-SAME:    (<vscale x 2 x i32> [[VD:%.*]], <vscale x 2 x i32> [[VS1:%.*]], <vscale x 2 x i32> [[VS2:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 2 x i32> @llvm.riscv.vmmacc.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[VD]], <vscale x 2 x i32> [[VS1]], <vscale x 2 x i32> [[VS2]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vmmacc_vv_i32m1(vint32m1_t vd, vint32m1_t vs1,
                                    vint32m1_t vs2, size_t vl) {
  return __riscv_vmmacc_vv_i32m1(vd, vs1, vs2, vl);
}

// CHECK-LABEL: define dso_local <vscale x 2 x i32> @test_vmmacc_vv_i32m1_lm2
// CHECK-SAME:    (<vscale x 2 x i32> [[VD:%.*]], <vscale x 4 x i32> [[VS1:%.*]], <vscale x 4 x i32> [[VS2:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 2 x i32> @llvm.riscv.vmmacc.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> [[VD]], <vscale x 4 x i32> [[VS1]], <vscale x 4 x i32> [[VS2]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vmmacc_vv_i32m1_lm2(vint32m1_t vd, vint32m2_t vs1,
                                    vint32m2_t vs2, size_t vl) {
  return __riscv_vmmacc_vv_i32m1_lm2(vd, vs1, vs2, vl);
}

// CHECK-LABEL: define dso_local <vscale x 4 x i32> @test_vmmacc_vv_i32m2
// CHECK-SAME:    (<vscale x 4 x i32> [[VD:%.*]], <vscale x 2 x i32> [[VS1:%.*]], <vscale x 2 x i32> [[VS2:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 4 x i32> @llvm.riscv.vmmacc.nxv4i32.nxv2i32.i64(<vscale x 4 x i32> [[VD]], <vscale x 2 x i32> [[VS1]], <vscale x 2 x i32> [[VS2]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vmmacc_vv_i32m2(vint32m2_t vd, vint32m1_t vs1,
                                    vint32m1_t vs2, size_t vl) {
  return __riscv_vmmacc_vv_i32m2(vd, vs1, vs2, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i32> @test_vmmacc_vv_i32m4_lm8
// CHECK-SAME:    (<vscale x 8 x i32> [[VD:%.*]], <vscale x 16 x i32> [[VS1:%.*]], <vscale x 16 x i32> [[VS2:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 8 x i32> @llvm.riscv.vmmacc.nxv8i32.nxv16i32.i64(<vscale x 8 x i32> [[VD]], <vscale x 16 x i32> [[VS1]], <vscale x 16 x i32> [[VS2]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vmmacc_vv_i32m4_lm8(vint32m4_t vd, vint32m8_t vs1,
                                    vint32m8_t vs2, size_t vl) {
  return __riscv_vmmacc_vv_i32m4_lm8(vd, vs1, vs2, vl);
}

// CHECK-LABEL: define dso_local <vscale x 16 x i32> @test_vmmacc_vv_i32m8
// CHECK-SAME:    (<vscale x 16 x i32> [[VD:%.*]], <vscale x 2 x i32> [[VS1:%.*]], <vscale x 2 x i32> [[VS2:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 16 x i32> @llvm.riscv.vmmacc.nxv16i32.nxv2i32.i64(<vscale x 16 x i32> [[VD]], <vscale x 2 x i32> [[VS1]], <vscale x 2 x i32> [[VS2]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vmmacc_vv_i32m8(vint32m8_t vd, vint32m1_t vs1,
                                    vint32m1_t vs2, size_t vl) {
  return __riscv_vmmacc_vv_i32m8(vd, vs1, vs2, vl);
}

// --- Non-widening SEW coverage beyond i32 (Phase 5) ---

// CHECK-LABEL: define dso_local <vscale x 8 x i8> @test_vmmacc_vv_i8m1
// CHECK-SAME:    (<vscale x 8 x i8> [[VD:%.*]], <vscale x 8 x i8> [[VS1:%.*]], <vscale x 8 x i8> [[VS2:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 8 x i8> @llvm.riscv.vmmacc.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[VD]], <vscale x 8 x i8> [[VS1]], <vscale x 8 x i8> [[VS2]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vmmacc_vv_i8m1(vint8m1_t vd, vint8m1_t vs1,
                              vint8m1_t vs2, size_t vl) {
  return __riscv_vmmacc_vv_i8m1(vd, vs1, vs2, vl);
}

// CHECK-LABEL: define dso_local <vscale x 64 x i8> @test_vmmacc_vv_i8m8_lm2
// CHECK-SAME:    (<vscale x 64 x i8> [[VD:%.*]], <vscale x 16 x i8> [[VS1:%.*]], <vscale x 16 x i8> [[VS2:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 64 x i8> @llvm.riscv.vmmacc.nxv64i8.nxv16i8.i64(<vscale x 64 x i8> [[VD]], <vscale x 16 x i8> [[VS1]], <vscale x 16 x i8> [[VS2]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vmmacc_vv_i8m8_lm2(vint8m8_t vd, vint8m2_t vs1,
                                  vint8m2_t vs2, size_t vl) {
  return __riscv_vmmacc_vv_i8m8_lm2(vd, vs1, vs2, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i16> @test_vmmacc_vv_i16m2_lm4
// CHECK-SAME:    (<vscale x 8 x i16> [[VD:%.*]], <vscale x 16 x i16> [[VS1:%.*]], <vscale x 16 x i16> [[VS2:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 8 x i16> @llvm.riscv.vmmacc.nxv8i16.nxv16i16.i64(<vscale x 8 x i16> [[VD]], <vscale x 16 x i16> [[VS1]], <vscale x 16 x i16> [[VS2]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vmmacc_vv_i16m2_lm4(vint16m2_t vd, vint16m4_t vs1,
                                    vint16m4_t vs2, size_t vl) {
  return __riscv_vmmacc_vv_i16m2_lm4(vd, vs1, vs2, vl);
}

// CHECK-LABEL: define dso_local <vscale x 4 x i64> @test_vmmacc_vv_i64m4
// CHECK-SAME:    (<vscale x 4 x i64> [[VD:%.*]], <vscale x 1 x i64> [[VS1:%.*]], <vscale x 1 x i64> [[VS2:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 4 x i64> @llvm.riscv.vmmacc.nxv4i64.nxv1i64.i64(<vscale x 4 x i64> [[VD]], <vscale x 1 x i64> [[VS1]], <vscale x 1 x i64> [[VS2]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vmmacc_vv_i64m4(vint64m4_t vd, vint64m1_t vs1,
                                vint64m1_t vs2, size_t vl) {
  return __riscv_vmmacc_vv_i64m4(vd, vs1, vs2, vl);
}

// CHECK-LABEL: define dso_local <vscale x 1 x i64> @test_vmmacc_vv_i64m1_lm8
// CHECK-SAME:    (<vscale x 1 x i64> [[VD:%.*]], <vscale x 8 x i64> [[VS1:%.*]], <vscale x 8 x i64> [[VS2:%.*]], i64 noundef [[VL:%.*]]) {{.*}} {
// CHECK:         [[TMP0:%.*]] = tail call <vscale x 1 x i64> @llvm.riscv.vmmacc.nxv1i64.nxv8i64.i64(<vscale x 1 x i64> [[VD]], <vscale x 8 x i64> [[VS1]], <vscale x 8 x i64> [[VS2]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vmmacc_vv_i64m1_lm8(vint64m1_t vd, vint64m8_t vs1,
                                    vint64m8_t vs2, size_t vl) {
  return __riscv_vmmacc_vv_i64m1_lm8(vd, vs1, vs2, vl);
}
