// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// (!srcloc operands relaxed by hand.)
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -target-feature +zvfbfmin \
// RUN:   -target-feature +experimental-zvvfmm -disable-O0-optnone \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | FileCheck %s

#pragma clang riscv intrinsic zvvm_vector

#include <riscv_vector.h>

// IME (Zvvm) OFP8 vector types: vfloat8e4m3{mf8..m8,m16}_t and
// vfloat8e5m2{...}_t. LLVM IR has no FP8 type, so they lower to the i8
// container (<vscale x N x i8>; m16 is the byte-typed 2-field tuple). The
// generic RVV utilities (vget/vset/vcreate/vundefined/vlmul_ext/vlmul_trunc/
// vreinterpret) and the m16 pair/unpair cover them.

// CHECK-LABEL: define dso_local <vscale x 1 x i8> @test_pass_e4m3mf8(
// CHECK-SAME: <vscale x 1 x i8> [[V:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret <vscale x 1 x i8> [[V]]
//
vfloat8e4m3mf8_t test_pass_e4m3mf8(vfloat8e4m3mf8_t v) { return v; }

// CHECK-LABEL: define dso_local <vscale x 8 x i8> @test_pass_e4m3m1(
// CHECK-SAME: <vscale x 8 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[V]]
//
vfloat8e4m3m1_t test_pass_e4m3m1(vfloat8e4m3m1_t v) { return v; }

// CHECK-LABEL: define dso_local <vscale x 64 x i8> @test_pass_e5m2m8(
// CHECK-SAME: <vscale x 64 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret <vscale x 64 x i8> [[V]]
//
vfloat8e5m2m8_t test_pass_e5m2m8(vfloat8e5m2m8_t v) { return v; }

// CHECK-LABEL: define dso_local <vscale x 32 x i8> @test_vget_v_f8e4m3m8_f8e4m3m4(
// CHECK-SAME: <vscale x 64 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.vector.extract.nxv32i8.nxv64i8(<vscale x 64 x i8> [[SRC]], i64 32)
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vfloat8e4m3m4_t test_vget_v_f8e4m3m8_f8e4m3m4(vfloat8e4m3m8_t src) {
  return __riscv_vget_v_f8e4m3m8_f8e4m3m4(src, 1);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i8> @test_vget_v_f8e5m2m4_f8e5m2m1(
// CHECK-SAME: <vscale x 32 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.vector.extract.nxv8i8.nxv32i8(<vscale x 32 x i8> [[SRC]], i64 24)
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vfloat8e5m2m1_t test_vget_v_f8e5m2m4_f8e5m2m1(vfloat8e5m2m4_t src) {
  return __riscv_vget_f8e5m2m1(src, 3);
}

// CHECK-LABEL: define dso_local <vscale x 64 x i8> @test_vset_v_f8e4m3m4_f8e4m3m8(
// CHECK-SAME: <vscale x 64 x i8> [[DEST:%.*]], <vscale x 32 x i8> [[VAL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.vector.insert.nxv64i8.nxv32i8(<vscale x 64 x i8> [[DEST]], <vscale x 32 x i8> [[VAL]], i64 32)
// CHECK-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vfloat8e4m3m8_t test_vset_v_f8e4m3m4_f8e4m3m8(vfloat8e4m3m8_t dest,
                                               vfloat8e4m3m4_t val) {
  return __riscv_vset_v_f8e4m3m4_f8e4m3m8(dest, 1, val);
}

// CHECK-LABEL: define dso_local <vscale x 16 x i8> @test_vset_v_f8e5m2m1_f8e5m2m2(
// CHECK-SAME: <vscale x 16 x i8> [[DEST:%.*]], <vscale x 8 x i8> [[VAL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.vector.insert.nxv16i8.nxv8i8(<vscale x 16 x i8> [[DEST]], <vscale x 8 x i8> [[VAL]], i64 0)
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vfloat8e5m2m2_t test_vset_v_f8e5m2m1_f8e5m2m2(vfloat8e5m2m2_t dest,
                                               vfloat8e5m2m1_t val) {
  return __riscv_vset(dest, 0, val);
}

// CHECK-LABEL: define dso_local <vscale x 16 x i8> @test_vcreate_v_f8e4m3m1_f8e4m3m2(
// CHECK-SAME: <vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.vector.insert.nxv16i8.nxv8i8(<vscale x 16 x i8> poison, <vscale x 8 x i8> [[V0]], i64 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i8> @llvm.vector.insert.nxv16i8.nxv8i8(<vscale x 16 x i8> [[TMP0]], <vscale x 8 x i8> [[V1]], i64 8)
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP1]]
//
vfloat8e4m3m2_t test_vcreate_v_f8e4m3m1_f8e4m3m2(vfloat8e4m3m1_t v0,
                                                  vfloat8e4m3m1_t v1) {
  return __riscv_vcreate_v_f8e4m3m1_f8e4m3m2(v0, v1);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i8> @test_vundefined_f8e4m3m1(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret <vscale x 8 x i8> poison
//
vfloat8e4m3m1_t test_vundefined_f8e4m3m1(void) {
  return __riscv_vundefined_f8e4m3m1();
}

// CHECK-LABEL: define dso_local <vscale x 4 x i8> @test_vundefined_f8e5m2mf2(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret <vscale x 4 x i8> poison
//
vfloat8e5m2mf2_t test_vundefined_f8e5m2mf2(void) {
  return __riscv_vundefined_f8e5m2mf2();
}

// CHECK-LABEL: define dso_local <vscale x 32 x i8> @test_vlmul_ext_v_f8e4m3m1_f8e4m3m4(
// CHECK-SAME: <vscale x 8 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.vector.insert.nxv32i8.nxv8i8(<vscale x 32 x i8> poison, <vscale x 8 x i8> [[V]], i64 0)
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vfloat8e4m3m4_t test_vlmul_ext_v_f8e4m3m1_f8e4m3m4(vfloat8e4m3m1_t v) {
  return __riscv_vlmul_ext_v_f8e4m3m1_f8e4m3m4(v);
}

// CHECK-LABEL: define dso_local <vscale x 2 x i8> @test_vlmul_trunc_v_f8e5m2m1_f8e5m2mf4(
// CHECK-SAME: <vscale x 8 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.vector.extract.nxv2i8.nxv8i8(<vscale x 8 x i8> [[V]], i64 0)
// CHECK-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vfloat8e5m2mf4_t test_vlmul_trunc_v_f8e5m2m1_f8e5m2mf4(vfloat8e5m2m1_t v) {
  return __riscv_vlmul_trunc_f8e5m2mf4(v);
}

// vreinterpret is bit-preserving over the shared i8 container: no IR.
// CHECK-LABEL: define dso_local <vscale x 8 x i8> @test_vreinterpret_v_i8m1_f8e4m3m1(
// CHECK-SAME: <vscale x 8 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[V]]
//
vfloat8e4m3m1_t test_vreinterpret_v_i8m1_f8e4m3m1(vint8m1_t v) {
  return __riscv_vreinterpret_v_i8m1_f8e4m3m1(v);
}

// CHECK-LABEL: define dso_local <vscale x 32 x i8> @test_vreinterpret_v_f8e4m3m4_u8m4(
// CHECK-SAME: <vscale x 32 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret <vscale x 32 x i8> [[V]]
//
vuint8m4_t test_vreinterpret_v_f8e4m3m4_u8m4(vfloat8e4m3m4_t v) {
  return __riscv_vreinterpret_v_f8e4m3m4_u8m4(v);
}

// CHECK-LABEL: define dso_local <vscale x 4 x i8> @test_vreinterpret_v_f8e5m2mf2_i8mf2(
// CHECK-SAME: <vscale x 4 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret <vscale x 4 x i8> [[V]]
//
vint8mf2_t test_vreinterpret_v_f8e5m2mf2_i8mf2(vfloat8e5m2mf2_t v) {
  return __riscv_vreinterpret_i8mf2(v);
}

// CHECK-LABEL: define dso_local <vscale x 64 x i8> @test_vreinterpret_v_u8m8_f8e5m2m8(
// CHECK-SAME: <vscale x 64 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret <vscale x 64 x i8> [[V]]
//
vfloat8e5m2m8_t test_vreinterpret_v_u8m8_f8e5m2m8(vuint8m8_t v) {
  return __riscv_vreinterpret_f8e5m2m8(v);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i8> @test_vreinterpret_v_f8e4m3m1_f8e5m2m1(
// CHECK-SAME: <vscale x 8 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[V]]
//
vfloat8e5m2m1_t test_vreinterpret_v_f8e4m3m1_f8e5m2m1(vfloat8e4m3m1_t v) {
  return __riscv_vreinterpret_v_f8e4m3m1_f8e5m2m1(v);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i8> @test_vreinterpret_v_f8e5m2m1_f8e4m3m1(
// CHECK-SAME: <vscale x 8 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[V]]
//
vfloat8e4m3m1_t test_vreinterpret_v_f8e5m2m1_f8e4m3m1(vfloat8e5m2m1_t v) {
  return __riscv_vreinterpret_f8e4m3m1(v);
}

// m16 accumulator: pair/unpair of two m8 halves.
// CHECK-LABEL: define dso_local target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @test_ime_vpair_f8e4m3m16(
// CHECK-SAME: <vscale x 64 x i8> [[LO:%.*]], <vscale x 64 x i8> [[HI:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv64i8_2t.nxv64i8(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) poison, <vscale x 64 x i8> [[LO]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv64i8_2t.nxv64i8(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) [[TMP0]], <vscale x 64 x i8> [[HI]], i32 1)
// CHECK-NEXT:    ret target("riscv.vector.tuple", <vscale x 64 x i8>, 2) [[TMP1]]
//
vfloat8e4m3m16_t test_ime_vpair_f8e4m3m16(vfloat8e4m3m8_t lo,
                                          vfloat8e4m3m8_t hi) {
  return __riscv_ime_vpair_f8e4m3m16(lo, hi);
}

// CHECK-LABEL: define dso_local <vscale x 64 x i8> @test_ime_vunpairhi_f8e5m2m16(
// CHECK-SAME: target("riscv.vector.tuple", <vscale x 64 x i8>, 2) [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.tuple.extract.nxv64i8.triscv.vector.tuple_nxv64i8_2t(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) [[SRC]], i32 1)
// CHECK-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vfloat8e5m2m8_t test_ime_vunpairhi_f8e5m2m16(vfloat8e5m2m16_t src) {
  return __riscv_ime_vunpairhi(src);
}

// Inline asm: the "vr" / "=vr" constraints accept the OFP8 types (the
// FlashAttention kernel's narrow_to_e4m3 / Zvfofp8min pattern).
// CHECK-LABEL: define dso_local <vscale x 8 x i8> @test_asm_narrow(
// CHECK-SAME: <vscale x 4 x bfloat> [[X:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> asm "vsetvli x0,$2,e8,mf2,ta,ma\0A\09vfncvtbf16.sat.f.f.w $0,$1", "=^vr,^vr,r"(<vscale x 4 x bfloat> [[X]], i64 [[VL]]) #[[ATTR2:[0-9]+]], !srcloc {{![0-9]+}}
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vfloat8e4m3m1_t test_asm_narrow(vbfloat16m1_t x, size_t vl) {
  vfloat8e4m3m1_t y;
  __asm__("vsetvli x0,%2,e8,mf2,ta,ma\n\tvfncvtbf16.sat.f.f.w %0,%1"
          : "=vr"(y)
          : "vr"(x), "r"(vl));
  return y;
}

// CHECK-LABEL: define dso_local <vscale x 32 x i8> @test_asm_m4(
// CHECK-SAME: <vscale x 32 x i8> [[A:%.*]], <vscale x 32 x i8> [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> asm "vmv4r.v $0, $1", "=^vr,^vr"(<vscale x 32 x i8> [[B]]) #[[ATTR2]], !srcloc {{![0-9]+}}
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vfloat8e5m2m4_t test_asm_m4(vfloat8e5m2m4_t a, vfloat8e4m3m4_t b) {
  vfloat8e5m2m4_t r;
  __asm__("vmv4r.v %0, %1" : "=vr"(r) : "vr"(b));
  (void)a;
  return r;
}
