; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+v,+experimental-zvvi32mm,+experimental-zvvmtls \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

; The Zvvm matrix vtype-state writers (llvm.riscv.vsetlambda,
; llvm.riscv.vsetvl.matrix) read and write inaccessible memory, and the
; readers (query_lambda, MACs, tile loads/stores) read it. Check that the
; writes survive with their result unused, that identical writes and
; identical reads separated by a write are not CSE'd (SelectionDAG CSE would
; merge chain-less nodes), and that readers stay on the correct side of the
; writes.

declare i64 @llvm.riscv.vsetlambda.i64(i64)
declare i64 @llvm.riscv.query.lambda.i64()
declare i64 @llvm.riscv.vsetvl.matrix.i64(i64, i64 immarg, i64 immarg,
  i64 immarg, i64 immarg, i64 immarg, i64 immarg, i64 immarg, i64 immarg)
declare <vscale x 2 x i32> @llvm.riscv.vmmacc.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, i64)
declare <vscale x 2 x i32> @llvm.riscv.vmtl.nxv2i32.p0.i64(
  <vscale x 2 x i32>, ptr, i64, i64)
declare void @llvm.riscv.vmts.nxv2i32.p0.i64(
  <vscale x 2 x i32>, ptr, i64, i64)

; A lambda write whose result is unused must still be emitted.
define void @vsetlambda_unused() nounwind {
; CHECK-LABEL: vsetlambda_unused:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a0, vtype
; CHECK-NEXT:    li a1, 7
; CHECK-NEXT:    slli a1, a1, 60
; CHECK-NEXT:    not a1, a1
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    li a1, 5
; CHECK-NEXT:    slli a1, a1, 60
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    csrr a1, vl
; CHECK-NEXT:    vsetvl a1, a1, a0
; CHECK-NEXT:    csrr a0, vtype
; CHECK-NEXT:    srli a0, a0, 60
; CHECK-NEXT:    andi a0, a0, 7
; CHECK-NEXT:    ret
  %r = call i64 @llvm.riscv.vsetlambda.i64(i64 5)
  ret void
}

; Same for a full matrix vtype write (SEW=16, LMUL=4, lambda=L16).
define void @vsetvl_matrix_unused(i64 %avl) nounwind {
; CHECK-LABEL: vsetvl_matrix_unused:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 5
; CHECK-NEXT:    slli a1, a1, 60
; CHECK-NEXT:    addi a1, a1, 202
; CHECK-NEXT:    vsetvl a1, a0, a1
; CHECK-NEXT:    ret
  %vl = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %avl, i64 1, i64 2,
          i64 1, i64 1, i64 5, i64 0, i64 0, i64 0)
  ret void
}

; Two identical lambda writes are both emitted.
define i64 @vsetlambda_twice() nounwind {
; CHECK-LABEL: vsetlambda_twice:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a0, vtype
; CHECK-NEXT:    li a1, 7
; CHECK-NEXT:    slli a1, a1, 60
; CHECK-NEXT:    not a1, a1
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    li a1, 5
; CHECK-NEXT:    slli a1, a1, 60
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    csrr a1, vl
; CHECK-NEXT:    vsetvl a1, a1, a0
; CHECK-NEXT:    csrr a0, vtype
; CHECK-NEXT:    srli a0, a0, 60
; CHECK-NEXT:    andi a0, a0, 7
; CHECK-NEXT:    csrr a1, vtype
; CHECK-NEXT:    li a2, 7
; CHECK-NEXT:    slli a2, a2, 60
; CHECK-NEXT:    not a2, a2
; CHECK-NEXT:    and a1, a1, a2
; CHECK-NEXT:    li a2, 5
; CHECK-NEXT:    slli a2, a2, 60
; CHECK-NEXT:    or a1, a1, a2
; CHECK-NEXT:    csrr a2, vl
; CHECK-NEXT:    vsetvl a2, a2, a1
; CHECK-NEXT:    csrr a1, vtype
; CHECK-NEXT:    srli a1, a1, 60
; CHECK-NEXT:    andi a1, a1, 7
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ret
  %x = call i64 @llvm.riscv.vsetlambda.i64(i64 5)
  %y = call i64 @llvm.riscv.vsetlambda.i64(i64 5)
  %s = add i64 %x, %y
  ret i64 %s
}

; Two lambda queries separated by a write read vtype twice, on either side
; of the write.
define i64 @query_around_write() nounwind {
; CHECK-LABEL: query_around_write:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a0, vtype
; CHECK-NEXT:    srli a0, a0, 60
; CHECK-NEXT:    andi a0, a0, 7
; CHECK-NEXT:    csrr a1, vtype
; CHECK-NEXT:    li a2, 7
; CHECK-NEXT:    slli a2, a2, 60
; CHECK-NEXT:    not a2, a2
; CHECK-NEXT:    and a1, a1, a2
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    slli a2, a2, 60
; CHECK-NEXT:    or a1, a1, a2
; CHECK-NEXT:    csrr a2, vl
; CHECK-NEXT:    vsetvl a2, a2, a1
; CHECK-NEXT:    csrr a1, vtype
; CHECK-NEXT:    srli a1, a1, 60
; CHECK-NEXT:    andi a1, a1, 7
; CHECK-NEXT:    csrr a1, vtype
; CHECK-NEXT:    srli a1, a1, 60
; CHECK-NEXT:    andi a1, a1, 7
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ret
  %q1 = call i64 @llvm.riscv.query.lambda.i64()
  %w = call i64 @llvm.riscv.vsetlambda.i64(i64 3)
  %q2 = call i64 @llvm.riscv.query.lambda.i64()
  %s = add i64 %q1, %q2
  ret i64 %s
}

; Two identical MACs separated by a lambda write are distinct operations
; (they run under different lambda values) and are emitted on either side of
; the write.
define void @mac_around_write(<vscale x 2 x i32> %c, <vscale x 2 x i32> %a,
; CHECK-LABEL: mac_around_write:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a4, 3
; CHECK-NEXT:    slli a4, a4, 60
; CHECK-NEXT:    addi a4, a4, 208
; CHECK-NEXT:    vsetvl a4, a0, a4
; CHECK-NEXT:    vmv1r.v v11, v8
; CHECK-NEXT:    vmmacc.vv v11, v9, v10
; CHECK-NEXT:    csrr a4, vtype
; CHECK-NEXT:    li a5, 7
; CHECK-NEXT:    slli a5, a5, 60
; CHECK-NEXT:    not a5, a5
; CHECK-NEXT:    and a4, a4, a5
; CHECK-NEXT:    li a5, 2
; CHECK-NEXT:    slli a5, a5, 60
; CHECK-NEXT:    or a4, a4, a5
; CHECK-NEXT:    csrr a5, vl
; CHECK-NEXT:    vsetvl a5, a5, a4
; CHECK-NEXT:    csrr a4, vtype
; CHECK-NEXT:    srli a4, a4, 60
; CHECK-NEXT:    andi a4, a4, 7
; CHECK-NEXT:    vmmacc.vv v8, v9, v10
; CHECK-NEXT:    vmts.v v11, (a1), a3
; CHECK-NEXT:    vmts.v v8, (a2), a3
; CHECK-NEXT:    ret
                              <vscale x 2 x i32> %b, i64 %vl, ptr %p0,
                              ptr %p1, i64 %ld) nounwind {
  %vt = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %vl, i64 2, i64 0,
          i64 1, i64 1, i64 3, i64 0, i64 0, i64 0)
  %c1 = call <vscale x 2 x i32> @llvm.riscv.vmmacc.nxv2i32.nxv2i32(
          <vscale x 2 x i32> %c, <vscale x 2 x i32> %a,
          <vscale x 2 x i32> %b, i64 %vl)
  %w = call i64 @llvm.riscv.vsetlambda.i64(i64 2)
  %c2 = call <vscale x 2 x i32> @llvm.riscv.vmmacc.nxv2i32.nxv2i32(
          <vscale x 2 x i32> %c, <vscale x 2 x i32> %a,
          <vscale x 2 x i32> %b, i64 %vl)
  call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> %c1, ptr %p0,
                                            i64 %ld, i64 %vl)
  call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> %c2, ptr %p1,
                                            i64 %ld, i64 %vl)
  ret void
}

; Two identical tile loads (which use vtype.lambda) separated by a lambda
; write are both emitted, each after its own write.
define void @tile_load_around_write(ptr %src, i64 %ld, i64 %vl, ptr %p0,
; CHECK-LABEL: tile_load_around_write:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a5, vtype
; CHECK-NEXT:    li a6, 7
; CHECK-NEXT:    slli a6, a6, 60
; CHECK-NEXT:    not a6, a6
; CHECK-NEXT:    and a5, a5, a6
; CHECK-NEXT:    li a6, 3
; CHECK-NEXT:    slli a6, a6, 60
; CHECK-NEXT:    or a5, a5, a6
; CHECK-NEXT:    csrr a6, vl
; CHECK-NEXT:    vsetvl a6, a6, a5
; CHECK-NEXT:    csrr a5, vtype
; CHECK-NEXT:    srli a5, a5, 60
; CHECK-NEXT:    andi a5, a5, 7
; CHECK-NEXT:    vmtl.v v8, (a0), a1
; CHECK-NEXT:    csrr a5, vtype
; CHECK-NEXT:    li a6, 7
; CHECK-NEXT:    slli a6, a6, 60
; CHECK-NEXT:    not a6, a6
; CHECK-NEXT:    and a5, a5, a6
; CHECK-NEXT:    li a6, 2
; CHECK-NEXT:    slli a6, a6, 60
; CHECK-NEXT:    or a5, a5, a6
; CHECK-NEXT:    csrr a6, vl
; CHECK-NEXT:    vsetvl a6, a6, a5
; CHECK-NEXT:    csrr a5, vtype
; CHECK-NEXT:    srli a5, a5, 60
; CHECK-NEXT:    andi a5, a5, 7
; CHECK-NEXT:    vmtl.v v9, (a0), a1
; CHECK-NEXT:    vmts.v v8, (a3), a1
; CHECK-NEXT:    vmts.v v9, (a4), a1
; CHECK-NEXT:    ret
                                    ptr %p1) nounwind {
  %w0 = call i64 @llvm.riscv.vsetlambda.i64(i64 3)
  %t0 = call <vscale x 2 x i32> @llvm.riscv.vmtl.nxv2i32.p0.i64(
          <vscale x 2 x i32> poison, ptr %src, i64 %ld, i64 %vl)
  %w1 = call i64 @llvm.riscv.vsetlambda.i64(i64 2)
  %t1 = call <vscale x 2 x i32> @llvm.riscv.vmtl.nxv2i32.p0.i64(
          <vscale x 2 x i32> poison, ptr %src, i64 %ld, i64 %vl)
  call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> %t0, ptr %p0,
                                            i64 %ld, i64 %vl)
  call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> %t1, ptr %p1,
                                            i64 %ld, i64 %vl)
  ret void
}

; A tile store issued before a lambda write stays before it.
define void @tile_store_around_write(<vscale x 2 x i32> %v, ptr %p, i64 %ld,
; CHECK-LABEL: tile_store_around_write:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmts.v v8, (a0), a1
; CHECK-NEXT:    csrr a3, vtype
; CHECK-NEXT:    li a4, 7
; CHECK-NEXT:    slli a4, a4, 60
; CHECK-NEXT:    not a4, a4
; CHECK-NEXT:    and a3, a3, a4
; CHECK-NEXT:    li a4, 2
; CHECK-NEXT:    slli a4, a4, 60
; CHECK-NEXT:    or a3, a3, a4
; CHECK-NEXT:    csrr a4, vl
; CHECK-NEXT:    vsetvl a4, a4, a3
; CHECK-NEXT:    csrr a3, vtype
; CHECK-NEXT:    srli a3, a3, 60
; CHECK-NEXT:    andi a3, a3, 7
; CHECK-NEXT:    vmts.v v8, (a0), a1
; CHECK-NEXT:    ret
                                     i64 %vl) nounwind {
  call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> %v, ptr %p,
                                            i64 %ld, i64 %vl)
  %w = call i64 @llvm.riscv.vsetlambda.i64(i64 2)
  call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> %v, ptr %p,
                                            i64 %ld, i64 %vl)
  ret void
}
