; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v,+zvfh,+experimental-zvfbfa,+experimental-zvvfp16mm,+experimental-zvvbf16mm \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

; Interaction of the Zvvm FP MACs with Zvfbfa code, which shares vtype.altfmt
; (e16alt = BF16 arithmetic). The MACs' accumulator-format demand must be
; honoured in both directions.

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"

; Zvfbfa BF16 arithmetic (e16alt) followed by an FP16-accumulator MAC: the
; MAC must get altfmt cleared.
define <vscale x 4 x half> @zvfbfa_then_fp16_mac(<vscale x 4 x bfloat> %x, <vscale x 4 x bfloat> %y, ptr %p, <vscale x 4 x half> %c, <vscale x 4 x half> %a, <vscale x 4 x half> %b, i64 %avl) {
; CHECK-LABEL: zvfbfa_then_fp16_mac:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 200
; CHECK-NEXT:    vsetvl a2, a1, a2
; CHECK-NEXT:    vsetvli zero, zero, e16alt, m1, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v9
; CHECK-NEXT:    vs1r.v v8, (a0)
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vfmmacc.vv v10, v11, v12
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %vl = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %avl, i64 1, i64 0, i64 1, i64 1, i64 0, i64 0, i64 0, i64 0)
  %s = call <vscale x 4 x bfloat> @llvm.riscv.vfadd.nxv4bf16.nxv4bf16.i64(<vscale x 4 x bfloat> poison, <vscale x 4 x bfloat> %x, <vscale x 4 x bfloat> %y, i64 7, i64 %vl)
  store <vscale x 4 x bfloat> %s, ptr %p
  %r = call <vscale x 4 x half> @llvm.riscv.vfmmacc.nxv4f16.nxv4f16.i64(<vscale x 4 x half> %c, <vscale x 4 x half> %a, <vscale x 4 x half> %b, i64 %vl)
  ret <vscale x 4 x half> %r
}

; Zvfbfa BF16 arithmetic followed by a BF16-accumulator MAC: altfmt is
; already set, no further vsetvli.
define <vscale x 4 x bfloat> @zvfbfa_then_bf16_mac(<vscale x 4 x bfloat> %x, <vscale x 4 x bfloat> %y, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %avl) {
; CHECK-LABEL: zvfbfa_then_bf16_mac:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 3
; CHECK-NEXT:    slli a1, a1, 57
; CHECK-NEXT:    addi a1, a1, 200
; CHECK-NEXT:    vsetvl a1, a0, a1
; CHECK-NEXT:    vsetvli zero, zero, e16alt, m1, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v9
; CHECK-NEXT:    vfmmacc.vv v8, v10, v11
; CHECK-NEXT:    ret
entry:
  %vl = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %avl, i64 1, i64 0, i64 1, i64 1, i64 0, i64 0, i64 1, i64 1)
  %s = call <vscale x 4 x bfloat> @llvm.riscv.vfadd.nxv4bf16.nxv4bf16.i64(<vscale x 4 x bfloat> poison, <vscale x 4 x bfloat> %x, <vscale x 4 x bfloat> %y, i64 7, i64 %vl)
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vfmmacc.nxv4bf16.nxv4bf16.i64(<vscale x 4 x bfloat> %s, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl)
  ret <vscale x 4 x bfloat> %r
}

; BF16-accumulator MAC followed by Zvfbfa BF16 arithmetic: both want e16alt,
; one transition only.
define <vscale x 4 x bfloat> @bf16_mac_then_zvfbfa(<vscale x 4 x bfloat> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, <vscale x 4 x bfloat> %y, i64 %avl) {
; CHECK-LABEL: bf16_mac_then_zvfbfa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 3
; CHECK-NEXT:    slli a1, a1, 57
; CHECK-NEXT:    addi a1, a1, 200
; CHECK-NEXT:    vsetvl a1, a0, a1
; CHECK-NEXT:    vsetvli zero, zero, e16alt, m1, ta, ma
; CHECK-NEXT:    vfmmacc.vv v8, v9, v10
; CHECK-NEXT:    vfadd.vv v8, v8, v11
; CHECK-NEXT:    ret
entry:
  %vl = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %avl, i64 1, i64 0, i64 1, i64 1, i64 0, i64 0, i64 1, i64 1)
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vfmmacc.nxv4bf16.nxv4bf16.i64(<vscale x 4 x bfloat> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl)
  %s = call <vscale x 4 x bfloat> @llvm.riscv.vfadd.nxv4bf16.nxv4bf16.i64(<vscale x 4 x bfloat> poison, <vscale x 4 x bfloat> %r, <vscale x 4 x bfloat> %y, i64 7, i64 %vl)
  ret <vscale x 4 x bfloat> %s
}
