; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v,+zvfh,+zvfbfmin,+experimental-zvvfp16mm,+experimental-zvvbf16mm,+experimental-zvvofp8fp16mm,+experimental-zvvofp8bf16mm,+experimental-zvvbf16fp32mm,+experimental-zvvbf16fp64mm,+experimental-zvvxofp8bf16mm,+experimental-zvvxi8bf16mm,+experimental-zvvxi8fp16mm \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

; BFloat16 accumulators and inputs on the Zvvm FP MACs.
;
; Per the IME spec the FP accumulator format is selected by vtype.altfmt (the
; Zvfbfa bit) together with SEW: SEW=16 with altfmt=0 is IEEE binary16, with
; altfmt=1 BFloat16 (and altfmt=1 is reserved at SEW=32/64). vsetvl_matrix
; cannot write altfmt, so RISCVInsertVSETVLI establishes it from the IR
; accumulator type: e16alt before a BF16-accumulator MAC, altfmt cleared
; before an FP16 / FP32 / FP64 one. Since altfmt's meaning depends on SEW, an
; FP MAC also demands its accumulator SEW, its A/B LMUL and its VL; a
; correctly-programmed vsetvl_matrix already supplies those, leaving altfmt as
; the only field the pass has to change. The input formats (altfmt_A /
; altfmt_B = 1 for BF16 inputs) remain caller state, like integer signedness.
;
; Only the Zvfbfmin type support (not Zvfbfa) is enabled here: e16alt must
; still print symbolically because the Zvvm BF16 extensions define altfmt.

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"

;===------------------------------------------------------------------------===;
; One cell per new spec row (entry state unknown: the MAC establishes its full
; vtype, tail-undisturbed).
;===------------------------------------------------------------------------===;

; vfmmacc.vv BF16 <- BF16, BF16 (Zvvbf16mm). EMUL_C = 1, LMUL = 1.
define <vscale x 4 x bfloat> @vfmmacc_bf16m1(<vscale x 4 x bfloat> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl) {
; CHECK-LABEL: vfmmacc_bf16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16alt, m1, tu, ma
; CHECK-NEXT:    vfmmacc.vv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vfmmacc.nxv4bf16.nxv4bf16.i64(<vscale x 4 x bfloat> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl)
  ret <vscale x 4 x bfloat> %r
}

; vfmmacc.vv BF16 <- BF16 at EMUL_C = 4, LMUL = 2.
define <vscale x 16 x bfloat> @vfmmacc_bf16m4_lm2(<vscale x 16 x bfloat> %c, <vscale x 8 x bfloat> %a, <vscale x 8 x bfloat> %b, i64 %vl) {
; CHECK-LABEL: vfmmacc_bf16m4_lm2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16alt, m2, tu, ma
; CHECK-NEXT:    vfmmacc.vv v8, v12, v14
; CHECK-NEXT:    ret
entry:
  %r = call <vscale x 16 x bfloat> @llvm.riscv.vfmmacc.nxv16bf16.nxv8bf16.i64(<vscale x 16 x bfloat> %c, <vscale x 8 x bfloat> %a, <vscale x 8 x bfloat> %b, i64 %vl)
  ret <vscale x 16 x bfloat> %r
}

; vfwmmacc.vv BF16 <- OFP8, OFP8 (Zvvofp8bf16mm; I8 container).
define <vscale x 4 x bfloat> @vfwmmacc_bf16m1_ofp8m1(<vscale x 4 x bfloat> %c, <vscale x 8 x i8> %a, <vscale x 8 x i8> %b, i64 %vl) {
; CHECK-LABEL: vfwmmacc_bf16m1_ofp8m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16alt, m1, tu, ma
; CHECK-NEXT:    vfwmmacc.vv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vfwmmacc.nxv4bf16.nxv8i8.i64(<vscale x 4 x bfloat> %c, <vscale x 8 x i8> %a, <vscale x 8 x i8> %b, i64 %vl)
  ret <vscale x 4 x bfloat> %r
}

; vfwmmacc.vv FP32 <- BF16, BF16 (Zvvbf16fp32mm): altfmt = 0.
define <vscale x 2 x float> @vfwmmacc_f32m1_bf16m1(<vscale x 2 x float> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl) {
; CHECK-LABEL: vfwmmacc_f32m1_bf16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, tu, ma
; CHECK-NEXT:    vfwmmacc.vv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %r = call <vscale x 2 x float> @llvm.riscv.vfwmmacc.nxv2f32.nxv4bf16.i64(<vscale x 2 x float> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl)
  ret <vscale x 2 x float> %r
}

; vfqmmacc.vv FP64 <- BF16, BF16 (Zvvbf16fp64mm): altfmt = 0.
define <vscale x 2 x double> @vfqmmacc_f64m2_bf16m2(<vscale x 2 x double> %c, <vscale x 8 x bfloat> %a, <vscale x 8 x bfloat> %b, i64 %vl) {
; CHECK-LABEL: vfqmmacc_f64m2_bf16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, tu, ma
; CHECK-NEXT:    vfqmmacc.vv v8, v10, v12
; CHECK-NEXT:    ret
entry:
  %r = call <vscale x 2 x double> @llvm.riscv.vfqmmacc.nxv2f64.nxv8bf16.i64(<vscale x 2 x double> %c, <vscale x 8 x bfloat> %a, <vscale x 8 x bfloat> %b, i64 %vl)
  ret <vscale x 2 x double> %r
}

; vfwmmacc.vv vm=0 BF16 <- MXFP8 (Zvvxofp8bf16mm).
define <vscale x 4 x bfloat> @vfwmmacc_scaled_bf16m1_ofp8m1(<vscale x 4 x bfloat> %c, <vscale x 8 x i8> %a, <vscale x 8 x i8> %b, <vscale x 4 x i16> %scale, i64 %vl) {
; CHECK-LABEL: vfwmmacc_scaled_bf16m1_ofp8m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16alt, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v0, v11
; CHECK-NEXT:    vfwmmacc.vv v8, v9, v10, v0.scale
; CHECK-NEXT:    ret
entry:
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vfwmmacc.scaled.nxv4bf16.nxv8i8.i64(<vscale x 4 x bfloat> %c, <vscale x 8 x i8> %a, <vscale x 8 x i8> %b, <vscale x 4 x i16> %scale, i64 0, i64 %vl)
  ret <vscale x 4 x bfloat> %r
}

; vfwimmacc.vv BF16 <- MXINT8 (Zvvxi8bf16mm).
define <vscale x 4 x bfloat> @vfwimmacc_bf16m1_i8m1(<vscale x 4 x bfloat> %c, <vscale x 8 x i8> %a, <vscale x 8 x i8> %b, <vscale x 4 x i16> %scale, i64 %vl) {
; CHECK-LABEL: vfwimmacc_bf16m1_i8m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16alt, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v0, v11
; CHECK-NEXT:    vfwimmacc.vv v8, v9, v10, v0.scale
; CHECK-NEXT:    ret
entry:
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vfwimmacc.nxv4bf16.nxv8i8.i64(<vscale x 4 x bfloat> %c, <vscale x 8 x i8> %a, <vscale x 8 x i8> %b, <vscale x 4 x i16> %scale, i64 1, i64 %vl)
  ret <vscale x 4 x bfloat> %r
}

; m16 accumulator, BF16 <- BF16 (vfmmacc_m16 with nxv*bf16 inputs is
; unambiguous: e16alt, LMUL = 1).
define target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @vfmmacc_m16_bf16(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl) {
; CHECK-LABEL: vfmmacc_m16_bf16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8r.v v16, (a1)
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    slli a3, a3, 3
; CHECK-NEXT:    add a1, a1, a3
; CHECK-NEXT:    vl8r.v v24, (a1)
; CHECK-NEXT:    vsetvli zero, a2, e16alt, m1, tu, ma
; CHECK-NEXT:    vfmmacc.vv v16, v8, v9
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    vs8r.v v16, (a0)
; CHECK-NEXT:    vs8r.v v24, (a3)
; CHECK-NEXT:    ret
entry:
  %r = call target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.vfmmacc.m16.triscv.vector.tuple_nxv64i8_2t.nxv4bf16.i64(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl)
  ret target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %r
}

; m16 accumulator, FP32 <- BF16 (e32, altfmt = 0).
define target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @vfwmmacc_m16_f32_bf16(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl) {
; CHECK-LABEL: vfwmmacc_m16_f32_bf16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8r.v v16, (a1)
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    slli a3, a3, 3
; CHECK-NEXT:    add a1, a1, a3
; CHECK-NEXT:    vl8r.v v24, (a1)
; CHECK-NEXT:    vsetvli zero, a2, e32, m1, tu, ma
; CHECK-NEXT:    vfwmmacc.vv v16, v8, v9
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    vs8r.v v16, (a0)
; CHECK-NEXT:    vs8r.v v24, (a3)
; CHECK-NEXT:    ret
entry:
  %r = call target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.vfwmmacc.m16.triscv.vector.tuple_nxv64i8_2t.nxv4bf16.i64(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl)
  ret target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %r
}

; m16 accumulator, FP64 <- BF16 (e64, altfmt = 0).
define target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @vfqmmacc_m16_f64_bf16(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl) {
; CHECK-LABEL: vfqmmacc_m16_f64_bf16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8r.v v16, (a1)
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    slli a3, a3, 3
; CHECK-NEXT:    add a1, a1, a3
; CHECK-NEXT:    vl8r.v v24, (a1)
; CHECK-NEXT:    vsetvli zero, a2, e64, m1, tu, ma
; CHECK-NEXT:    vfqmmacc.vv v16, v8, v9
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    vs8r.v v16, (a0)
; CHECK-NEXT:    vs8r.v v24, (a3)
; CHECK-NEXT:    ret
entry:
  %r = call target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.vfqmmacc.m16.triscv.vector.tuple_nxv64i8_2t.nxv4bf16.i64(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl)
  ret target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %r
}

;===------------------------------------------------------------------------===;
; altfmt transitions after a caller-issued vsetvl_matrix.
;===------------------------------------------------------------------------===;

; vsetvl_matrix(e16, m1, ta, ma, lambda=0, altfmt_A=B=1) programs everything
; but altfmt (0). The BF16-accumulator MAC needs e16alt; SEW / LMUL / VL /
; matrix fields already match, so a VL-preserving vsetvli that flips only
; altfmt is emitted after the register-form vsetvl.
define <vscale x 4 x bfloat> @matrix_bf16_after_vsetvl_matrix(<vscale x 4 x bfloat> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %avl) {
; CHECK-LABEL: matrix_bf16_after_vsetvl_matrix:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 3
; CHECK-NEXT:    slli a1, a1, 57
; CHECK-NEXT:    addi a1, a1, 200
; CHECK-NEXT:    vsetvl a1, a0, a1
; CHECK-NEXT:    vsetvli zero, zero, e16alt, m1, ta, ma
; CHECK-NEXT:    vfmmacc.vv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %vl = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %avl, i64 1, i64 0, i64 1, i64 1, i64 0, i64 0, i64 1, i64 1)
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vfmmacc.nxv4bf16.nxv4bf16.i64(<vscale x 4 x bfloat> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl)
  ret <vscale x 4 x bfloat> %r
}

; Same with a selected lambda (L4): the tracked matrix state is preserved, and
; the altfmt-only transition is still a plain `vsetvli zero, zero` (same SEW,
; so hardware keeps lambda; bs / altfmt_A / altfmt_B are retained verbatim),
; not a second register-form vsetvl.
define <vscale x 4 x bfloat> @matrix_bf16_lambda_after_vsetvl_matrix(<vscale x 4 x bfloat> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %avl) {
; CHECK-LABEL: matrix_bf16_lambda_after_vsetvl_matrix:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 27
; CHECK-NEXT:    slli a1, a1, 57
; CHECK-NEXT:    addi a1, a1, 200
; CHECK-NEXT:    vsetvl a1, a0, a1
; CHECK-NEXT:    vsetvli zero, zero, e16alt, m1, ta, ma
; CHECK-NEXT:    vfmmacc.vv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %vl = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %avl, i64 1, i64 0, i64 1, i64 1, i64 3, i64 0, i64 1, i64 1)
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vfmmacc.nxv4bf16.nxv4bf16.i64(<vscale x 4 x bfloat> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl)
  ret <vscale x 4 x bfloat> %r
}

; FP32 <- BF16 after vsetvl_matrix(e32, altfmt_A=B=1): altfmt is already 0,
; nothing is inserted.
define <vscale x 2 x float> @matrix_f32_bf16_after_vsetvl_matrix(<vscale x 2 x float> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %avl) {
; CHECK-LABEL: matrix_f32_bf16_after_vsetvl_matrix:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 27
; CHECK-NEXT:    slli a1, a1, 57
; CHECK-NEXT:    addi a1, a1, 208
; CHECK-NEXT:    vsetvl a1, a0, a1
; CHECK-NEXT:    vfwmmacc.vv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %vl = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %avl, i64 2, i64 0, i64 1, i64 1, i64 3, i64 0, i64 1, i64 1)
  %r = call <vscale x 2 x float> @llvm.riscv.vfwmmacc.nxv2f32.nxv4bf16.i64(<vscale x 2 x float> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl)
  ret <vscale x 2 x float> %r
}

; FP16 -> BF16 -> FP16 accumulation under one vsetvl_matrix(e16): no vsetvli
; before the first MAC, e16alt before the BF16 one, e16 again before the last.
define <vscale x 4 x half> @matrix_fp16_bf16_fp16(<vscale x 4 x half> %c, <vscale x 4 x half> %a, <vscale x 4 x half> %b, <vscale x 4 x bfloat> %cb, <vscale x 4 x bfloat> %ab, <vscale x 4 x bfloat> %bb, ptr %p, i64 %avl) {
; CHECK-LABEL: matrix_fp16_bf16_fp16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 200
; CHECK-NEXT:    vsetvl a2, a1, a2
; CHECK-NEXT:    vfmmacc.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e16alt, m1, ta, ma
; CHECK-NEXT:    vfmmacc.vv v11, v12, v13
; CHECK-NEXT:    vs1r.v v11, (a0)
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vfmmacc.vv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %vl = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %avl, i64 1, i64 0, i64 1, i64 1, i64 0, i64 0, i64 0, i64 0)
  %c1 = call <vscale x 4 x half> @llvm.riscv.vfmmacc.nxv4f16.nxv4f16.i64(<vscale x 4 x half> %c, <vscale x 4 x half> %a, <vscale x 4 x half> %b, i64 %vl)
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vfmmacc.nxv4bf16.nxv4bf16.i64(<vscale x 4 x bfloat> %cb, <vscale x 4 x bfloat> %ab, <vscale x 4 x bfloat> %bb, i64 %vl)
  store <vscale x 4 x bfloat> %r, ptr %p
  %c2 = call <vscale x 4 x half> @llvm.riscv.vfmmacc.nxv4f16.nxv4f16.i64(<vscale x 4 x half> %c1, <vscale x 4 x half> %a, <vscale x 4 x half> %b, i64 %vl)
  ret <vscale x 4 x half> %c2
}

; FP16 accumulator (OFP8 inputs) right after a BF16 one (OFP8 inputs) and
; the MXINT8 pair: each FP16 MAC must clear altfmt again.
define <vscale x 4 x half> @matrix_bf16_then_fp16_ofp8(<vscale x 4 x bfloat> %cb, <vscale x 4 x half> %ch, <vscale x 8 x i8> %a, <vscale x 8 x i8> %b, <vscale x 4 x i16> %scale, ptr %p, i64 %avl) {
; CHECK-LABEL: matrix_bf16_then_fp16_ofp8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v0, v12
; CHECK-NEXT:    li a2, 200
; CHECK-NEXT:    vsetvl a2, a1, a2
; CHECK-NEXT:    vsetvli zero, zero, e16alt, m1, ta, ma
; CHECK-NEXT:    vfwmmacc.vv v8, v10, v11
; CHECK-NEXT:    vs1r.v v8, (a0)
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vfwmmacc.vv v9, v10, v11
; CHECK-NEXT:    vsetvli zero, zero, e16alt, m1, ta, ma
; CHECK-NEXT:    vfwimmacc.vv v8, v10, v11, v0.scale
; CHECK-NEXT:    vs1r.v v8, (a0)
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vfwimmacc.vv v9, v10, v11, v0.scale
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    ret
entry:
  %vl = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %avl, i64 1, i64 0, i64 1, i64 1, i64 0, i64 0, i64 0, i64 0)
  %r0 = call <vscale x 4 x bfloat> @llvm.riscv.vfwmmacc.nxv4bf16.nxv8i8.i64(<vscale x 4 x bfloat> %cb, <vscale x 8 x i8> %a, <vscale x 8 x i8> %b, i64 %vl)
  store <vscale x 4 x bfloat> %r0, ptr %p
  %h0 = call <vscale x 4 x half> @llvm.riscv.vfwmmacc.nxv4f16.nxv8i8.i64(<vscale x 4 x half> %ch, <vscale x 8 x i8> %a, <vscale x 8 x i8> %b, i64 %vl)
  %r1 = call <vscale x 4 x bfloat> @llvm.riscv.vfwimmacc.nxv4bf16.nxv8i8.i64(<vscale x 4 x bfloat> %r0, <vscale x 8 x i8> %a, <vscale x 8 x i8> %b, <vscale x 4 x i16> %scale, i64 0, i64 %vl)
  store <vscale x 4 x bfloat> %r1, ptr %p
  %h1 = call <vscale x 4 x half> @llvm.riscv.vfwimmacc.nxv4f16.nxv8i8.i64(<vscale x 4 x half> %h0, <vscale x 8 x i8> %a, <vscale x 8 x i8> %b, <vscale x 4 x i16> %scale, i64 0, i64 %vl)
  ret <vscale x 4 x half> %h1
}

; A standard FP16 vector op after a BF16 MAC: vfadd.vv (IS_NOT_ALTFMT) gets
; altfmt cleared again.
define <vscale x 4 x half> @matrix_bf16_then_vfadd_f16(<vscale x 4 x bfloat> %cb, <vscale x 4 x bfloat> %ab, <vscale x 4 x bfloat> %bb, <vscale x 4 x half> %x, <vscale x 4 x half> %y, ptr %p, i64 %avl) {
; CHECK-LABEL: matrix_bf16_then_vfadd_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    slli a2, a2, 57
; CHECK-NEXT:    addi a2, a2, 200
; CHECK-NEXT:    vsetvl a2, a1, a2
; CHECK-NEXT:    vsetvli zero, zero, e16alt, m1, ta, ma
; CHECK-NEXT:    vfmmacc.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vfadd.vv v9, v11, v12
; CHECK-NEXT:    vs1r.v v8, (a0)
; CHECK-NEXT:    vmv.v.v v8, v9
; CHECK-NEXT:    ret
entry:
  %vl = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %avl, i64 1, i64 0, i64 1, i64 1, i64 0, i64 0, i64 1, i64 1)
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vfmmacc.nxv4bf16.nxv4bf16.i64(<vscale x 4 x bfloat> %cb, <vscale x 4 x bfloat> %ab, <vscale x 4 x bfloat> %bb, i64 %vl)
  store <vscale x 4 x bfloat> %r, ptr %p
  %s = call <vscale x 4 x half> @llvm.riscv.vfadd.nxv4f16.nxv4f16.i64(<vscale x 4 x half> poison, <vscale x 4 x half> %x, <vscale x 4 x half> %y, i64 7, i64 %vl)
  ret <vscale x 4 x half> %s
}

; BF16 GEMM-style loop: vsetvl_matrix in the preheader, BF16 MAC in the loop.
; The preheader's vsetvl_matrix leaves altfmt = 0 (it has no altfmt operand)
; and PRE only hoists out of unknown-state predecessors, so the VL-preserving
; e16alt transition currently stays in the loop body — correct, but a
; vsetvl_matrix that can program altfmt would remove it.
define <vscale x 4 x bfloat> @matrix_bf16_loop(<vscale x 4 x bfloat> %c0, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %avl, i64 %n) {
; CHECK-LABEL: matrix_bf16_loop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    slli a2, a2, 57
; CHECK-NEXT:    addi a2, a2, 200
; CHECK-NEXT:    vsetvl a2, a0, a2
; CHECK-NEXT:  .LBB16_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vsetvli zero, zero, e16alt, m1, tu, ma
; CHECK-NEXT:    vfmmacc.vv v8, v9, v10
; CHECK-NEXT:    addi a1, a1, -1
; CHECK-NEXT:    bnez a1, .LBB16_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    ret
entry:
  %vl = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 %avl, i64 1, i64 0, i64 1, i64 1, i64 0, i64 0, i64 1, i64 1)
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %c = phi <vscale x 4 x bfloat> [ %c0, %entry ], [ %c.next, %loop ]
  %c.next = call <vscale x 4 x bfloat> @llvm.riscv.vfmmacc.nxv4bf16.nxv4bf16.i64(<vscale x 4 x bfloat> %c, <vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b, i64 %vl)
  %i.next = add i64 %i, 1
  %done = icmp eq i64 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret <vscale x 4 x bfloat> %c.next
}
