; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v,+experimental-zvvi32mm,+experimental-zvvi8i32mm,+experimental-zvvfp32mm -verify-machineinstrs < %s | FileCheck %s

; EMUL_C = 16 (m16 accumulator) matrix MACs. The accumulator is a
; 16-register-aligned pair of M8 groups held in the vector tuple type
; target("riscv.vector.tuple", <vscale x 64 x i8>, 2); only v0 and v16 are
; legal base registers. vtype (SEW / LMUL / lambda) is pre-established by a
; separate vsetvl_matrix in real code; these tests exercise ISel, register
; allocation, and MC lowering only.

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"

declare target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.vmmacc.m16.triscv.vector.tuple_nxv64i8_2t.nxv2i32.i64(target("riscv.vector.tuple", <vscale x 64 x i8>, 2), <vscale x 2 x i32>, <vscale x 2 x i32>, i64)
declare target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.vqmmacc.m16.triscv.vector.tuple_nxv64i8_2t.nxv16i8.i64(target("riscv.vector.tuple", <vscale x 64 x i8>, 2), <vscale x 16 x i8>, <vscale x 16 x i8>, i64)
declare target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.vfmmacc.m16.triscv.vector.tuple_nxv64i8_2t.nxv2f32.i64(target("riscv.vector.tuple", <vscale x 64 x i8>, 2), <vscale x 2 x float>, <vscale x 2 x float>, i64)
declare target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv64i8_2t.nxv16i32(target("riscv.vector.tuple", <vscale x 64 x i8>, 2), <vscale x 16 x i32>, i32)
declare <vscale x 16 x i32> @llvm.riscv.tuple.extract.nxv16i32.triscv.vector.tuple_nxv64i8_2t(target("riscv.vector.tuple", <vscale x 64 x i8>, 2), i32)

; W=1, SEW(C)=32, A/B LMUL=1.
define target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @vmmacc_m16_i32_lm1(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %vd, <vscale x 2 x i32> %vs1, <vscale x 2 x i32> %vs2, i64 %vl) {
; CHECK-LABEL: vmmacc_m16_i32_lm1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8r.v v16, (a1)
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    slli a3, a3, 3
; CHECK-NEXT:    add a1, a1, a3
; CHECK-NEXT:    vl8r.v v24, (a1)
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    vmmacc.vv v16, v8, v9
; CHECK-NEXT:    vs8r.v v16, (a0)
; CHECK-NEXT:    vs8r.v v24, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = call target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.vmmacc.m16.triscv.vector.tuple_nxv64i8_2t.nxv2i32.i64(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %vd, <vscale x 2 x i32> %vs1, <vscale x 2 x i32> %vs2, i64 %vl)
  ret target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %0
}

; W=4 (i8 inputs -> i32 accumulator), A/B LMUL=2.
define target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @vqmmacc_m16_i32_lm2(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %vd, <vscale x 16 x i8> %vs1, <vscale x 16 x i8> %vs2, i64 %vl) {
; CHECK-LABEL: vqmmacc_m16_i32_lm2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8r.v v16, (a1)
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    slli a3, a3, 3
; CHECK-NEXT:    add a1, a1, a3
; CHECK-NEXT:    vl8r.v v24, (a1)
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    vqmmacc.vv v16, v8, v10
; CHECK-NEXT:    vs8r.v v16, (a0)
; CHECK-NEXT:    vs8r.v v24, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = call target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.vqmmacc.m16.triscv.vector.tuple_nxv64i8_2t.nxv16i8.i64(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %vd, <vscale x 16 x i8> %vs1, <vscale x 16 x i8> %vs2, i64 %vl)
  ret target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %0
}

; FP W=1, SEW(C)=32, A/B LMUL=1.
define target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @vfmmacc_m16_f32_lm1(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %vd, <vscale x 2 x float> %vs1, <vscale x 2 x float> %vs2, i64 %vl) {
; CHECK-LABEL: vfmmacc_m16_f32_lm1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8r.v v16, (a1)
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    slli a3, a3, 3
; CHECK-NEXT:    add a1, a1, a3
; CHECK-NEXT:    vl8r.v v24, (a1)
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    vfmmacc.vv v16, v8, v9
; CHECK-NEXT:    vs8r.v v16, (a0)
; CHECK-NEXT:    vs8r.v v24, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = call target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.vfmmacc.m16.triscv.vector.tuple_nxv64i8_2t.nxv2f32.i64(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %vd, <vscale x 2 x float> %vs1, <vscale x 2 x float> %vs2, i64 %vl)
  ret target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %0
}

; Pair two m8 halves into an m16 accumulator (tuple inserts), run the MAC,
; and extract both halves — the pair/unpair pseudo-intrinsic lowering shape.
; With clean allocation this coalesces to zero whole-register moves around
; the MAC.
define <vscale x 16 x i32> @pair_mac_unpair(<vscale x 16 x i32> %lo, <vscale x 16 x i32> %hi, <vscale x 2 x i32> %vs1, <vscale x 2 x i32> %vs2, i64 %vl) {
; CHECK-LABEL: pair_mac_unpair:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl1re32.v v7, (a1)
; CHECK-NEXT:    vl1re32.v v6, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv8r.v v24, v16
; CHECK-NEXT:    vmv8r.v v16, v8
; CHECK-NEXT:    vmmacc.vv v16, v6, v7
; CHECK-NEXT:    vsetvli a0, zero, e32, m8, ta, ma
; CHECK-NEXT:    vadd.vv v8, v16, v24
; CHECK-NEXT:    ret
entry:
  %p0 = call target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv64i8_2t.nxv16i32(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) poison, <vscale x 16 x i32> %lo, i32 0)
  %p1 = call target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv64i8_2t.nxv16i32(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %p0, <vscale x 16 x i32> %hi, i32 1)
  %acc = call target("riscv.vector.tuple", <vscale x 64 x i8>, 2) @llvm.riscv.vmmacc.m16.triscv.vector.tuple_nxv64i8_2t.nxv2i32.i64(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %p1, <vscale x 2 x i32> %vs1, <vscale x 2 x i32> %vs2, i64 %vl)
  %outlo = call <vscale x 16 x i32> @llvm.riscv.tuple.extract.nxv16i32.triscv.vector.tuple_nxv64i8_2t(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %acc, i32 0)
  %outhi = call <vscale x 16 x i32> @llvm.riscv.tuple.extract.nxv16i32.triscv.vector.tuple_nxv64i8_2t(target("riscv.vector.tuple", <vscale x 64 x i8>, 2) %acc, i32 1)
  %sum = add <vscale x 16 x i32> %outlo, %outhi
  ret <vscale x 16 x i32> %sum
}
