; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 6
; RUN: opt -mtriple=riscv64 -mattr=+v,+experimental-zvvi32mm,+experimental-zvvmtls \
; RUN:   -O2 -S < %s | FileCheck %s

; IR-level modelling of the Zvvm matrix vtype state: the writers
; (vsetlambda / vsetvl_matrix) are `memory(inaccessiblemem: readwrite)`, the
; MACs and query_lambda `memory(inaccessiblemem: read)`, tile loads
; `memory(argmem: read, inaccessiblemem: read)` and tile stores
; `memory(argmem: write, inaccessiblemem: read)`. Ordinary RVV intrinsics
; (including llvm.riscv.vsetvli) stay `memory(none)`.

declare i64 @llvm.riscv.vsetvli.i64(i64, i64 immarg, i64 immarg)
declare i64 @llvm.riscv.vsetlambda.i64(i64)
declare i64 @llvm.riscv.query.lambda.i64()
declare i64 @llvm.riscv.vsetvl.matrix.i64(i64, i64 immarg, i64 immarg,
  i64 immarg, i64 immarg, i64 immarg, i64 immarg, i64 immarg, i64 immarg)
declare <vscale x 2 x i32> @llvm.riscv.vmmacc.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, i64)
declare <vscale x 2 x i32> @llvm.riscv.vadd.nxv2i32.nxv2i32.i64(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, i64)
declare <vscale x 2 x i32> @llvm.riscv.vmtl.nxv2i32.p0.i64(
  <vscale x 2 x i32>, ptr, i64, i64)
declare void @llvm.riscv.vmts.nxv2i32.p0.i64(
  <vscale x 2 x i32>, ptr, i64, i64)

; Reproducer: `__riscv_vsetvl_e16m4(1024); (void)__riscv_vsetlambda(16);`.
; The unused vsetvli folds away; the lambda writes must not.
define void @unused_write() {
; CHECK-LABEL: define void @unused_write(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR5:[0-9]+]] {
; CHECK-NEXT:    [[R:%.*]] = tail call i64 @llvm.riscv.vsetlambda.i64(i64 5)
; CHECK-NEXT:    [[M:%.*]] = tail call i64 @llvm.riscv.vsetvl.matrix.i64(i64 1024, i64 1, i64 2, i64 1, i64 1, i64 5, i64 0, i64 0, i64 0)
; CHECK-NEXT:    ret void
;
  %vl = call i64 @llvm.riscv.vsetvli.i64(i64 1024, i64 1, i64 2)
  %r = call i64 @llvm.riscv.vsetlambda.i64(i64 5)
  %m = call i64 @llvm.riscv.vsetvl.matrix.i64(i64 1024, i64 1, i64 2,
  i64 1, i64 1, i64 5, i64 0, i64 0, i64 0)
  ret void
}

; Reproducer: `x = __riscv_vsetlambda(16); __riscv_vsetvl_e32m4(512);
; y = __riscv_vsetlambda(16);` must keep both writes.
define i64 @write_not_cse() {
; CHECK-LABEL: define i64 @write_not_cse(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR5]] {
; CHECK-NEXT:    [[X:%.*]] = tail call i64 @llvm.riscv.vsetlambda.i64(i64 5)
; CHECK-NEXT:    [[Y:%.*]] = tail call i64 @llvm.riscv.vsetlambda.i64(i64 5)
; CHECK-NEXT:    [[S:%.*]] = add i64 [[Y]], [[X]]
; CHECK-NEXT:    ret i64 [[S]]
;
  %x = call i64 @llvm.riscv.vsetlambda.i64(i64 5)
  %vl = call i64 @llvm.riscv.vsetvli.i64(i64 512, i64 2, i64 2)
  %y = call i64 @llvm.riscv.vsetlambda.i64(i64 5)
  %s = add i64 %x, %y
  ret i64 %s
}

; query_lambda is CSE'd when no write intervenes, but not across a write.
define i64 @query_cse() {
; CHECK-LABEL: define i64 @query_cse(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR5]] {
; CHECK-NEXT:    [[Q1:%.*]] = tail call i64 @llvm.riscv.query.lambda.i64()
; CHECK-NEXT:    [[W:%.*]] = tail call i64 @llvm.riscv.vsetlambda.i64(i64 3)
; CHECK-NEXT:    [[Q3:%.*]] = tail call i64 @llvm.riscv.query.lambda.i64()
; CHECK-NEXT:    [[S1:%.*]] = shl i64 [[Q1]], 1
; CHECK-NEXT:    [[S2:%.*]] = add i64 [[Q3]], [[S1]]
; CHECK-NEXT:    ret i64 [[S2]]
;
  %q1 = call i64 @llvm.riscv.query.lambda.i64()
  %q2 = call i64 @llvm.riscv.query.lambda.i64()
  %w = call i64 @llvm.riscv.vsetlambda.i64(i64 3)
  %q3 = call i64 @llvm.riscv.query.lambda.i64()
  %s1 = add i64 %q1, %q2
  %s2 = add i64 %s1, %q3
  ret i64 %s2
}

; Identical MACs are CSE'd across an ordinary store, but not across a lambda
; write. (They are also not CSE'd across a tile-store call: its effects,
; argmem: write + inaccessiblemem: read, do not conflict with the MAC's, but
; call-vs-call alias analysis does not prove that.) The ordinary RVV vadd is
; CSE'd across the lambda write.
define void @mac_cse(<vscale x 2 x i32> %c, <vscale x 2 x i32> %a,
; CHECK-LABEL: define void @mac_cse(
; CHECK-SAME: <vscale x 2 x i32> [[C:%.*]], <vscale x 2 x i32> [[A:%.*]], <vscale x 2 x i32> [[B:%.*]], i64 [[VL:%.*]], ptr writeonly captures(none) [[P:%.*]], ptr writeonly captures(none) [[Q:%.*]], i64 [[LD:%.*]]) local_unnamed_addr #[[ATTR6:[0-9]+]] {
; CHECK-NEXT:    [[C1:%.*]] = tail call <vscale x 2 x i32> @llvm.riscv.vmmacc.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[C]], <vscale x 2 x i32> [[A]], <vscale x 2 x i32> [[B]], i64 [[VL]])
; CHECK-NEXT:    store <vscale x 2 x i32> [[C1]], ptr [[Q]], align 8
; CHECK-NEXT:    tail call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> [[C1]], ptr [[P]], i64 [[LD]], i64 [[VL]])
; CHECK-NEXT:    [[V1:%.*]] = tail call <vscale x 2 x i32> @llvm.riscv.vadd.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> poison, <vscale x 2 x i32> [[A]], <vscale x 2 x i32> [[B]], i64 [[VL]])
; CHECK-NEXT:    [[W:%.*]] = tail call i64 @llvm.riscv.vsetlambda.i64(i64 2)
; CHECK-NEXT:    [[C3:%.*]] = tail call <vscale x 2 x i32> @llvm.riscv.vmmacc.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[C]], <vscale x 2 x i32> [[A]], <vscale x 2 x i32> [[B]], i64 [[VL]])
; CHECK-NEXT:    tail call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> [[C3]], ptr [[P]], i64 [[LD]], i64 [[VL]])
; CHECK-NEXT:    tail call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> [[V1]], ptr [[P]], i64 [[LD]], i64 [[VL]])
; CHECK-NEXT:    ret void
;
  <vscale x 2 x i32> %b, i64 %vl, ptr %p, ptr %q,
  i64 %ld) {
  %c1 = call <vscale x 2 x i32> @llvm.riscv.vmmacc.nxv2i32.nxv2i32(
  <vscale x 2 x i32> %c, <vscale x 2 x i32> %a,
  <vscale x 2 x i32> %b, i64 %vl)
  store <vscale x 2 x i32> %c1, ptr %q
  %c2 = call <vscale x 2 x i32> @llvm.riscv.vmmacc.nxv2i32.nxv2i32(
  <vscale x 2 x i32> %c, <vscale x 2 x i32> %a,
  <vscale x 2 x i32> %b, i64 %vl)
  call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> %c2, ptr %p,
  i64 %ld, i64 %vl)
  %v1 = call <vscale x 2 x i32> @llvm.riscv.vadd.nxv2i32.nxv2i32.i64(
  <vscale x 2 x i32> poison, <vscale x 2 x i32> %a,
  <vscale x 2 x i32> %b, i64 %vl)
  %w = call i64 @llvm.riscv.vsetlambda.i64(i64 2)
  %c3 = call <vscale x 2 x i32> @llvm.riscv.vmmacc.nxv2i32.nxv2i32(
  <vscale x 2 x i32> %c, <vscale x 2 x i32> %a,
  <vscale x 2 x i32> %b, i64 %vl)
  call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> %c3, ptr %p,
  i64 %ld, i64 %vl)
  %v2 = call <vscale x 2 x i32> @llvm.riscv.vadd.nxv2i32.nxv2i32.i64(
  <vscale x 2 x i32> poison, <vscale x 2 x i32> %a,
  <vscale x 2 x i32> %b, i64 %vl)
  call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> %v1, ptr %p,
  i64 %ld, i64 %vl)
  call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> %v2, ptr %p,
  i64 %ld, i64 %vl)
  ret void
}

; A tile load is not hoisted out of a loop that writes lambda, even though
; its operands are loop-invariant and nothing in the loop stores to %src.
define void @tile_load_no_licm(ptr noalias %src, ptr noalias %dst, i64 %ld,
; CHECK-LABEL: define void @tile_load_no_licm(
; CHECK-SAME: ptr noalias readonly captures(none) [[SRC:%.*]], ptr noalias writeonly captures(none) [[DST:%.*]], i64 [[LD:%.*]], i64 [[VL:%.*]], i64 [[N:%.*]]) local_unnamed_addr #[[ATTR7:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[W:%.*]] = tail call i64 @llvm.riscv.vsetlambda.i64(i64 3)
; CHECK-NEXT:    [[T:%.*]] = tail call <vscale x 2 x i32> @llvm.riscv.vmtl.nxv2i32.p0.i64(<vscale x 2 x i32> poison, ptr [[SRC]], i64 [[LD]], i64 [[VL]])
; CHECK-NEXT:    [[Q:%.*]] = getelementptr i32, ptr [[DST]], i64 [[I]]
; CHECK-NEXT:    tail call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> [[T]], ptr [[Q]], i64 [[LD]], i64 [[VL]])
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
  i64 %vl, i64 %n) {
entry:
  br label %loop
loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %w = call i64 @llvm.riscv.vsetlambda.i64(i64 3)
  %t = call <vscale x 2 x i32> @llvm.riscv.vmtl.nxv2i32.p0.i64(
  <vscale x 2 x i32> poison, ptr %src, i64 %ld, i64 %vl)
  %q = getelementptr i32, ptr %dst, i64 %i
  call void @llvm.riscv.vmts.nxv2i32.p0.i64(<vscale x 2 x i32> %t, ptr %q,
  i64 %ld, i64 %vl)
  %i.next = add i64 %i, 1
  %done = icmp eq i64 %i.next, %n
  br i1 %done, label %exit, label %loop
exit:
  ret void
}
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { mustprogress nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite) "target-features"="+v,+experimental-zvvi32mm,+experimental-zvvmtls" }
; CHECK: attributes #[[ATTR1:[0-9]+]] = { mustprogress nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) "target-features"="+v,+experimental-zvvi32mm,+experimental-zvvmtls" }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { mustprogress nocallback nofree nosync nounwind willreturn memory(none) "target-features"="+v,+experimental-zvvi32mm,+experimental-zvvmtls" }
; CHECK: attributes #[[ATTR3:[0-9]+]] = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: read, inaccessiblemem: read) "target-features"="+v,+experimental-zvvi32mm,+experimental-zvvmtls" }
; CHECK: attributes #[[ATTR4:[0-9]+]] = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: write, inaccessiblemem: read) "target-features"="+v,+experimental-zvvi32mm,+experimental-zvvmtls" }
; CHECK: attributes #[[ATTR5]] = { mustprogress nofree norecurse nosync nounwind willreturn memory(inaccessiblemem: readwrite) "target-features"="+v,+experimental-zvvi32mm,+experimental-zvvmtls" }
; CHECK: attributes #[[ATTR6]] = { mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: write, inaccessiblemem: readwrite) "target-features"="+v,+experimental-zvvi32mm,+experimental-zvvmtls" }
; CHECK: attributes #[[ATTR7]] = { nofree norecurse nosync nounwind memory(argmem: readwrite, inaccessiblemem: readwrite) "target-features"="+v,+experimental-zvvi32mm,+experimental-zvvmtls" }
;.
